# CH02 Scikit-Learn

In [89]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold, StratifiedKFold, cross_val_score, cross_validate, train_test_split, GridSearchCV
import pandas as pd
import numpy as np

In [2]:
# Iris data set load
iris = load_iris()

In [3]:
iris_data = iris.data

In [4]:
# ndaraay 이므로 슬라이스로 데이터를 본다.
iris_data[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [5]:
iris_data.shape

(150, 4)

In [6]:
iris_label = iris.target

In [7]:
iris_label.shape

(150,)

In [8]:
# Target Names 
iris_name = iris.target_names

In [9]:
iris_name

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [10]:
# 데이터 셋 설명
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [11]:
# Columns Names
feature_names = iris.feature_names
feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [12]:
# Iris dataset ==> data frame
iris_df = pd.DataFrame(iris_data, columns=feature_names)
iris_df['label'] = iris_label

In [13]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

In [14]:
# 기초통계량
iris_df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)       label  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

In [15]:
x_train, x_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size = 0.2, random_state=11)

In [76]:
# 객체생성
dt_clf = DecisionTreeClassifier(random_state=11)

In [77]:
# 학습 최소한 10가지 이상의 경우를 만들어 조합을 해본다
dt_clf.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=11, splitter='best')

In [78]:
# 예측
pred = dt_clf.predict(x_test)
accuracy_score(y_test, pred)

0.98

In [79]:
pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2])

In [80]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2])

In [21]:
!jupyter --version

jupyter core     : 4.6.1
jupyter-notebook : 6.0.3
qtconsole        : 4.6.0
ipython          : 7.12.0
ipykernel        : 5.1.4
jupyter client   : 5.3.4
jupyter lab      : 1.2.6
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.4
traitlets        : 4.3.3


## Model Selection

In [22]:
# dt_clf = DecisionTreeClassifier()

In [23]:
pred2 = dt_clf.predict(x_train)
accuracy_score(y_train, pred2)

1.0

In [24]:
x_train, x_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size = 0.3, random_state=121)

In [25]:
dt_clf.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=11, splitter='best')

In [26]:
pred = dt_clf.predict(x_test)

In [27]:
accuracy_score(y_test, pred)

0.9555555555555556

## 교차검증 (KFOLD)

In [70]:
kfold = KFold(n_splits=5)
cv_accuracy = []
label = iris.target
features = iris.data
dt_clf = DecisionTreeClassifier(random_state=156)
print('붓꽃 데이터 세트 크기: ',features.shape[0])

붓꽃 데이터 세트 크기:  150


#### n_iter = 0
for train_index, test_index in kfold.split(features):
    x_train, x_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]

    dt_clf.fit(x_train, y_train)
    pred = dt_clf.predict(x_test)
    n_iter += 1

    accuracy = np.around(accuracy_score(y_test, pred), 4)

    train_size = x_train.shape[0]
    test_size = x_test.shape[0]
    print('\n{0} 교차검증 정확도: {1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'.format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증 세트 인덱스: {1}'.format(n_iter, test_index))
    cv_accuracy.append(accuracy)

print('\n## 평균 검증 정확도: ',np.mean(cv_accuracy))

## stratified K Fold

In [46]:
iris_df['label'].value_counts()

2    50
1    50
0    50
Name: label, dtype: int64

In [51]:
kfold = KFold(n_splits=3)
n_iter = 0

In [55]:
for train_index, test_index in kfold.split(iris_df):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print('## 교차 검증 : {0}'.format(n_iter))
    print('학습 레이블 데이터 분포 :\n',label_train.value_counts())    
    print('검증 레이블 데이터 분포:\n', label_test.value_counts())

## 교차 검증 : 7
학습 레이블 데이터 분포 :
 2    50
1    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    50
Name: label, dtype: int64
## 교차 검증 : 8
학습 레이블 데이터 분포 :
 2    50
0    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    50
Name: label, dtype: int64
## 교차 검증 : 9
학습 레이블 데이터 분포 :
 1    50
0    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 2    50
Name: label, dtype: int64


In [57]:
skf = StratifiedKFold(n_splits=3)
n_iter = 0

In [58]:
for train_index, test_index in skf.split(iris_df, iris_df['label']):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print('## 교차 검증 : {0}'.format(n_iter))
    print('학습 레이블 데이터 분포 :\n',label_train.value_counts())    
    print('검증 레이블 데이터 분포:\n', label_test.value_counts())

## 교차 검증 : 1
학습 레이블 데이터 분포 :
 2    34
1    33
0    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    17
0    17
2    16
Name: label, dtype: int64
## 교차 검증 : 2
학습 레이블 데이터 분포 :
 1    34
2    33
0    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 2    17
0    17
1    16
Name: label, dtype: int64
## 교차 검증 : 3
학습 레이블 데이터 분포 :
 0    34
2    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 2    17
1    17
0    16
Name: label, dtype: int64


In [74]:
skf = StratifiedKFold(n_splits=3)
cv_accuracy = []
label = iris.target
features = iris.data
dt_clf = DecisionTreeClassifier(random_state=156)
print('붓꽃 데이터 세트 크기: ',features.shape[0])

붓꽃 데이터 세트 크기:  150


In [75]:
n_iter = 0
for train_index, test_index in skf.split(features, label):
    x_train, x_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]

    dt_clf.fit(x_train, y_train)
    pred = dt_clf.predict(x_test)
    n_iter += 1

    accuracy = np.around(accuracy_score(y_test, pred), 4)

    train_size = x_train.shape[0]
    test_size = x_test.shape[0]
    print('\n{0} 교차검증 정확도: {1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'.format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증 세트 인덱스: {1}'.format(n_iter, test_index))
    cv_accuracy.append(accuracy)

print('\n## 교차 검증별 정확도', np.round(cv_accuracy, 4))
print('\n## 평균 검증 정확도: ',np.mean(cv_accuracy))


1 교차검증 정확도: 0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#1 검증 세트 인덱스: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

2 교차검증 정확도: 0.94, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#2 검증 세트 인덱스: [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

3 교차검증 정확도: 0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#3 검증 세트 인덱스: [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## 교차 검증별 정확도 [0.98 0.94 0.98]

## 평균 검증 정확도:  0.9666666666666667


## Cross_val_score()
### 교차 검증을 간편하게

In [86]:
iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

In [87]:
data = iris_data.data
label = iris_data.target

In [88]:
# 성능 지표는 정확도(Accuracy), 교차 검증 세트는 3개
scores = cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)
print('교차 검증별 정확도: ', np.round(scores, 4))
print('평균 검증 정확도: ', np.round(np.mean(scores), 4))

교차 검증별 정확도:  [0.98 0.94 0.98]
평균 검증 정확도:  0.9667


## GridSearchCV
### - 교차 검증과 최적 하이퍼파라미터 튜닝을 한번에

In [109]:
iris = load_iris()
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=121)

In [110]:
dtree = DecisionTreeClassifier()

In [111]:
parameters = {'max_depth':[1,2,3,4,5], 'min_samples_split':[2,3,4,5]}

In [106]:
grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True)
grid_dtree.fit(x_train, y_train)

scores_df=pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score', 'split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  \
0   {'max_depth': 1, 'min_samples_split': 2}         0.700000   
1   {'max_depth': 1, 'min_samples_split': 3}         0.700000   
2   {'max_depth': 1, 'min_samples_split': 4}         0.700000   
3   {'max_depth': 1, 'min_samples_split': 5}         0.700000   
4   {'max_depth': 1, 'min_samples_split': 7}         0.700000   
5   {'max_depth': 1, 'min_samples_split': 8}         0.700000   
6   {'max_depth': 1, 'min_samples_split': 9}         0.700000   
7   {'max_depth': 2, 'min_samples_split': 2}         0.958333   
8   {'max_depth': 2, 'min_samples_split': 3}         0.958333   
9   {'max_depth': 2, 'min_samples_split': 4}         0.958333   
10  {'max_depth': 2, 'min_samples_split': 5}         0.958333   
11  {'max_depth': 2, 'min_samples_split': 7}         0.958333   
12  {'max_depth': 2, 'min_samples_split': 8}         0.958333   
13  {'max_depth': 2, 'min_samples_split': 9}         0.958333   
14  {'max_depth': 3, 'min_samples_split': 2}         0.975000   
15  {'max_depth': 3, 'min_samples_split': 3}         0.975000   
16  {'max_depth': 3, 'min_samples_split': 4}         0.975000   
17  {'max_depth': 3, 'min_samples_split': 5}         0.975000   
18  {'max_depth': 3, 'min_samples_split': 7}         0.975000   
19  {'max_depth': 3, 'min_samples_split': 8}         0.975000   
20  {'max_depth': 3, 'min_samples_split': 9}         0.975000   
21  {'max_depth': 4, 'min_samples_split': 2}         0.966667   
22  {'max_depth': 4, 'min_samples_split': 3}         0.950000   
23  {'max_depth': 4, 'min_samples_split': 4}         0.966667   
24  {'max_depth': 4, 'min_samples_split': 5}         0.966667   
25  {'max_depth': 4, 'min_samples_split': 7}         0.966667   
26  {'max_depth': 4, 'min_samples_split': 8}         0.966667   
27  {'max_depth': 4, 'min_samples_split': 9}         0.966667   
28  {'max_depth': 5, 'min_samples_split': 2}         0.950000   
29  {'max_depth': 5, 'min_samples_split': 3}         0.950000   
30  {'max_depth': 5, 'min_samples_split': 4}         0.966667   
31  {'max_depth': 5, 'min_samples_split': 5}         0.966667   
32  {'max_depth': 5, 'min_samples_split': 7}         0.966667   
33  {'max_depth': 5, 'min_samples_split': 8}         0.966667   
34  {'max_depth': 5, 'min_samples_split': 9}         0.966667   

    rank_test_score  split0_test_score  split1_test_score  split2_test_score  
0                29              0.700                0.7              0.700  
1                29              0.700                0.7              0.700  
2                29              0.700                0.7              0.700  
3                29              0.700                0.7              0.700  
4                29              0.700                0.7              0.700  
5                29              0.700                0.7              0.700  
6                29              0.700                0.7              0.700  
7                19              0.925                1.0              0.950  
8                19              0.925                1.0              0.950  
9                19              0.925                1.0              0.950  
10               19              0.925                1.0              0.950  
11               19              0.925                1.0              0.950  
12               19              0.925                1.0              0.950  
13               19              0.925                1.0              0.950  
14                1              0.975                1.0              0.950  
15                1              0.975                1.0              0.950  
16                1              0.975                1.0              0.950  
17                1              0.975                1.0              0.950  
18                1              0.975                1.0              0.950  
19                1              0.975                1.0              0.950  
20                1              0.975

In [99]:
scores_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.000665  4.702465e-04         0.000332         0.00047   
1       0.000332  4.700217e-04         0.000000         0.00000   
2       0.000998  1.946680e-07         0.000000         0.00000   
3       0.000000  0.000000e+00         0.000000         0.00000   
4       0.000332  4.701340e-04         0.000333         0.00047   
5       0.000332  4.701340e-04         0.000332         0.00047   

  param_max_depth param_min_samples_split  \
0               1                       2   
1               1                       3   
2               2                       2   
3               2                       3   
4               3                       2   
5               3                       3   

                                     params  split0_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}              0.700   
1  {'max_depth': 1, 'min_samples_split': 3}              0.700   
2  {'max_depth': 2, 'min_samples_split': 2}              0.925   
3  {'max_depth': 2, 'min_samples_split': 3}              0.925   
4  {'max_depth': 3, 'min_samples_split': 2}              0.975   
5  {'max_depth': 3, 'min_samples_split': 3}              0.975   

   split1_test_score  split2_test_score  mean_test_score  std_test_score  \
0                0.7               0.70         0.700000    1.110223e-16   
1                0.7               0.70         0.700000    1.110223e-16   
2                1.0               0.95         0.958333    3.118048e-02   
3                1.0               0.95         0.958333    3.118048e-02   
4                1.0               0.95         0.975000    2.041241e-02   
5                1.0               0.95         0.975000    2.041241e-02   

   rank_test_score  
0                5  
1                5  
2                3  
3                3  
4                1  
5                1

In [107]:
print('GridSearchCV 최적 파라미터:', grid_dtree.best_params_)
print('GridSearchCV 최고 정확도: {0:.4f}'.format(grid_dtree.best_score_))

GridSearchCV 최적 파라미터: {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도: 0.9750


In [108]:
estimator = grid_dtree.best_estimator_

pred = estimator.predict(x_test)
print('테스트 데이터 세트 정확도 : {0:.4f}'.format(accuracy_score(y_test,pred)))

테스트 데이터 세트 정확도 : 0.9667


### 데이터 전처리
. 레이블 인코딩

In [2]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import numpy as np
import pandas as pd

In [3]:
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

In [5]:
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변경값: ', labels)

인코딩 변경값:  [0 1 4 5 3 3 2 2]


In [6]:
# fit() + transform()  = fit_transform()
labels = encoder.fit_transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2], dtype=int64)

In [7]:
encoder.classes_

array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

In [9]:
encoder.inverse_transform([4,5,2,0,1,1,3,3])

array(['전자레인지', '컴퓨터', '믹서', 'TV', '냉장고', '냉장고', '선풍기', '선풍기'],
      dtype='<U5')

In [10]:
def get_name(model, num):
    return model.inverse_transform([num])[0]

get_name(encoder, 3)

'선풍기'

### One-Hot encoding

In [17]:
# 숫자 값으로 변환하기 위해 Label Enocoder를 사용
encoder = LabelEncoder()

# 변환과 동시에 maxtrix로 변환
labels = encoder.fit_transform(items).reshape(-1, 1)

In [18]:
# One-hot encoding
oh_encoder = OneHotEncoder()
oh_labels = oh_encoder.fit_transform(labels)
print('One-Hot encoding Data')
print(oh_labels.toarray())
print('One-Hot Encoding shape')
print(oh_labels.shape)


One-Hot encoding Data
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
One-Hot Encoding shape
(8, 6)


In [19]:
df = pd.DataFrame({'item':items})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

## Feature Scaling & Normalization

In [20]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import pandas as pd
import numpy as np

In [30]:
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(iris_data, None ,iris.feature_names)

In [31]:
print('Feature들의 평균 값')
print(iris_df.mean())

Feature들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64


In [26]:
print('Feature들의 분산 값')
print(iris_df.var())

Feature들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [32]:
print('Feature들의 편차 값')
print(iris_df.std())

Feature들의 편차 값
sepal length (cm)    0.828066
sepal width (cm)     0.435866
petal length (cm)    1.765298
petal width (cm)     0.762238
dtype: float64


In [42]:
# StandardScaler

scaler = StandardScaler()
iris_scaled = scaler.fit_transform(iris_df)
print(iris_scaled.shape)
iris_scaled_df = pd.DataFrame(iris_scaled, None, iris.feature_names)
iris_scaled_df.head()

(150, 4)


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0          -0.900681          1.019004          -1.340227         -1.315444
1          -1.143017         -0.131979          -1.340227         -1.315444
2          -1.385353          0.328414          -1.397064         -1.315444
3          -1.506521          0.098217          -1.283389         -1.315444
4          -1.021849          1.249201          -1.340227         -1.315444

In [41]:
print('표준화 한 Feature들의 평균 값')
print(iris_scaled_df.mean())

표준화 한 Feature들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64


In [36]:
print('표준화 한 Feature들의 편차 값')
print(iris_scaled_df.std())

표준화 한 Feature들의 편차 값
sepal length (cm)    1.00335
sepal width (cm)     1.00335
petal length (cm)    1.00335
petal width (cm)     1.00335
dtype: float64


In [39]:
print('표준화 한 Feature들의 분산 값')
print(iris_scaled_df.var())

표준화 한 Feature들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


### MinMax Scaler

In [43]:
scaler = MinMaxScaler()
iris_scaled = scaler.fit_transform(iris_df)

In [44]:
iris_scaled_df = pd.DataFrame(iris_scaled, None, iris.feature_names)
iris_scaled_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0           0.222222          0.625000           0.067797          0.041667
1           0.166667          0.416667           0.067797          0.041667
2           0.111111          0.500000           0.050847          0.041667
3           0.083333          0.458333           0.084746          0.041667
4           0.194444          0.666667           0.067797          0.041667

In [45]:
print('MinMaxScale한 Feature들의 평균 값')
print(iris_scaled_df.mean())

MinMaxScale한 Feature들의 평균 값
sepal length (cm)    0.428704
sepal width (cm)     0.440556
petal length (cm)    0.467458
petal width (cm)     0.458056
dtype: float64


In [46]:
print('MinMaxScale한 Feature들의 편차 값')
print(iris_scaled_df.std())

MinMaxScale한 Feature들의 편차 값
sepal length (cm)    0.230018
sepal width (cm)     0.181611
petal length (cm)    0.299203
petal width (cm)     0.317599
dtype: float64


In [48]:
print('MinMaxScale한 Feature들의 분산 값')
print(iris_scaled_df.var())

MinMaxScale한 Feature들의 분산 값
sepal length (cm)    0.052908
sepal width (cm)     0.032983
petal length (cm)    0.089522
petal width (cm)     0.100869
dtype: float64


In [49]:
print('MinMaxScale한 Feature들의 최소값')
print(iris_scaled_df.min())

MinMaxScale한 Feature들의 최소값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64


In [50]:
print('MinMaxScale한 Feature들의 최대값')
print(iris_scaled_df.max())

MinMaxScale한 Feature들의 최대값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64
