# CH04 Classification

### Logistic Regression

In [1]:
import numpy as np
import pandas as pd
import warnings
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor, export_graphviz
import graphviz
warnings.filterwarnings('ignore')

In [2]:
iris = load_iris()

In [3]:
# data, target , target_names, DESCR, feature_names, filename
data = iris.data
label = iris.target
columns =iris.feature_names
df = pd.DataFrame(data, columns=columns)

In [4]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [5]:
x_train, x_test, y_train, y_test = train_test_split(data, label, test_size = 0.2, shuffle=True, stratify=label, random_state=2019)

In [6]:
lr = LogisticRegression(verbose=1)

In [7]:
lr.fit(x_train, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=1,
                   warm_start=False)

In [8]:
pred = lr.predict(x_test)

In [9]:
# 로지스틸 회귀 정확도
accuracy_score(y_test, pred)

0.9666666666666667

In [10]:
# 계수(weight)
lr.coef_

array([[-0.4331758 ,  0.82135237, -2.39403865, -0.96776796],
       [ 0.49039201, -0.29955397, -0.15924469, -0.91532022],
       [-0.05721621, -0.5217984 ,  2.55328334,  1.88308818]])

In [11]:
# Bias
lr.intercept_

array([  9.79503679,   2.02943481, -11.8244716 ])

In [12]:
svc = SVC()

In [13]:
svc.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [14]:
pred = svc.predict(x_test)

In [15]:
accuracy_score(y_test, pred)

0.9666666666666667

In [16]:
pred

array([1, 1, 2, 2, 2, 0, 0, 0, 0, 0, 1, 0, 2, 1, 2, 2, 0, 1, 0, 0, 2, 2,
       1, 0, 1, 2, 1, 2, 1, 2])

In [17]:
y_test

array([1, 1, 2, 2, 2, 0, 0, 0, 0, 0, 1, 0, 2, 1, 2, 2, 0, 1, 0, 0, 2, 2,
       1, 0, 1, 2, 1, 1, 1, 2])

In [18]:
dtc = DecisionTreeClassifier()

In [19]:
dtc.fit(x_train, y_train)
dtc_pred = dtc.predict(x_test)
accuracy_score(y_test, dtc_pred)

0.9666666666666667

In [20]:
dtr = DecisionTreeRegressor()
dtr.fit(x_train, y_train)
dtr_pred = dtr.predict(x_test)
accuracy_score(y_test, dtr_pred)

0.9666666666666667

## Graphviz

In [21]:
export_graphviz(dtc, out_file="tree.dot", class_names=iris.target_names, feature_names=columns, impurity=True, filled=True)

In [22]:
with open("tree.dot") as f:
    dot_graph = f.read()
# graphviz.Source(dot_graph)

In [23]:
graphviz.Source(dot_graph)

ExecutableNotFound: failed to execute ['dot', '-Tsvg'], make sure the Graphviz executables are on your systems' PATH