In [1]:
from sklearn.preprocessing import LabelEncoder


In [2]:
itmes=['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']


In [3]:
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변경값: ', labels)


NameError: name 'items' is not defined

In [4]:
encoder = LabelEncoder()


In [5]:
encoder.fit(items)


NameError: name 'items' is not defined

In [6]:
encoder = LabelEncoder()


In [7]:
encoder.fit(items)


NameError: name 'items' is not defined

In [8]:
itees=['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']


In [9]:
items=['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']


In [10]:
encoder.fit(items)


LabelEncoder()

In [11]:
labels = encoder.transform(items)


In [12]:
print('인코딩 변경값: ', labels)


인코딩 변경값:  [0 1 4 5 3 3 2 2]


In [13]:
print('인코딩 클래스: ', encoder.classes_)


인코딩 클래스:  ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [14]:
print('디코딩 원본 값',  encoder.inverse_transform([4,5,2,0,1,1,3,3]))


디코딩 원본 값 ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


In [15]:
labels = labels.reshape(-1, 1)


In [16]:
labels


array([[0],
       [1],
       [4],
       [5],
       [3],
       [3],
       [2],
       [2]], dtype=int64)

In [17]:
oh_encoder = OneHotEncoder()


NameError: name 'OneHotEncoder' is not defined

In [18]:
oh_encoder = OneHotEncoder()


NameError: name 'OneHotEncoder' is not defined

In [19]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder


In [20]:
oh_encoder = OneHotEncoder()


In [21]:
oh_encoder.fit(labels)


OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='error', sparse=True)

In [22]:
oh_labels = oh_encoder.transform(labels)


In [23]:
print('One-Hot encoding Data')


One-Hot encoding Data


In [24]:
print(oh_labels.toarray())


[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [25]:
print('One-Hoe encoding Shape')


One-Hoe encoding Shape


In [26]:
print(oh_labels.shape)


(8, 6)


In [27]:
import pandas as pd


In [28]:
df = pd.DataFrame({'item':items})


In [29]:
df


item
0     TV
1    냉장고
2  전자레인지
3    컴퓨터
4    선풍기
5    선풍기
6     믹서
7     믹서

In [30]:
df = pd.DataFrame({'item':['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']})


In [31]:
df


item
0     TV
1    냉장고
2  전자레인지
3    컴퓨터
4    선풍기
5    선풍기
6     믹서
7     믹서

In [32]:
pd.get_dummies(df)


item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

In [33]:
df = pd.DataFrame({'item':items})


In [34]:
pd.get_dummies(df)


item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

In [35]:
# One-Hot Encoder API -> get_dummies()
